### ISSUE TITLE
[HU2] - Dependiente - Actualización de datos

### ISSUE THREAD

**Issue by josevilchez247** [josevilchez247/Odyssey#24]
Como dependiente de la gasolinera quiero poder actualizar el precio de la gasolina, para que los viajeros reciban información verificada

**Comment by JJ** [comment]
No es una historia de usuario porque no tiene ningún beneficio para el usuario. Y tiene que tener un título.

**Comment by josevilchez247** [comment]
El beneficio es que el precio estará actualizado y el usuario podrá tener información precisa

**Comment by JJ** [comment]
El dependiente no obtiene ningún beneficio. Sólo se escriben HUs para los clientes.
Tampoco es una buena idea que sean los dependientes quienes actualizan el precio para ti. Tendrás que buscar otra forma de hacerlo (pero en un issue, no una HU)
