### ISSUE TITLE
Los milestones no son válidos

### ISSUE THREAD

**Issue by JJ** [josevilchez247/Odyssey#27]
Ni corresponde el título al contenido, ni contienen un producto mínimamente viable, ni tienen asignados issues que tienen nada que ver con ellas. Ya está superado el objetivo 1, aunque posiblemente fuera error mío, ya que ni siquiera los describes en el README.md. Como no podemos volver atrás, sí podemos pedir que lo hagas ahora. Sin productos mínimamente viables bien descritos, no puedes avanzar en el desarrollo, y no puedes hacer correctamente los objetivos a partir del 3: #26

**Comment by josevilchez247** [comment]
Ya he añadido las historias de usuario al readme lo tenia creado el fichero pero no estaba añadido al README.md fallo mío

**Comment by josevilchez247** [comment]
Los milestone que tengo describen las tareas que tengo que abordar creación de estructuras de datos para recoger y almacenar los datos de viajeros, trabajadores y gasolineras, luego la elaboración de un algoritmo que calcule la ruta optima para ir de A a B gracias a los datos de las gasolineras y del viajero y automatización de tareas.

**Comment by JJ** [comment]
Literalmente os hemos dicho varias veces que los milestones *no* son tareas. Por eso no son válidos.

**Comment by josevilchez247** [comment]
He modificado los milestones con lo que hablamos ayer en la tutoría

**Comment by josevilchez247** [comment]
@JJ ya he corregido las cosas que me comento esta listo para la revisión
